---
name: Build new machine image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to build the image in
        type: choice
        options: [ErikSandbox]
        required: true
        default: ErikSandbox
      recreate_template:
        description: Recreate the template  if it already exists
        type: boolean
        required: true
        default: false
      build_image_from_template:
        description: Build a new image from the template
        type: boolean
        required: true
        default: true
      image_name:
        description: Name of the image to build
        default: auto-neurodamus
        required: true
        type: string
      image_version:
        description: Version of the image to build
        default: 3.8.1
        required: true
        type: string
env:
  GALLERY_NAME: ${{ vars.GALLERY_NAME }}
  IDENTITY_NAME: ${{ vars.IDENTITY_NAME }}
  IMAGE_NAME: ${{ inputs.image_name }}
  IMAGE_ROLE_DEF_NAME: ${{ vars.IMAGE_ROLE_DEF_NAME }}
  IMAGE_VERSION: ${{ inputs.image_version }}
  LOCATION: ${{ vars.LOCATION }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  RUN_OUTPUT_NAME: ${{ vars.RUN_OUTPUT_NAME }}
  SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TEMPLATE_IMAGE_BUILDER_ID: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourcegroups/${{
    vars.RESOURCE_GROUP_NAME }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${{
    vars.IDENTITY_NAME }}
permissions:
  id-token: write
  contents: read
jobs:
  ensure-environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install azure-cli
        run: |-
          sudo apt-get update
          sudo apt-get install -y azure-cli
      - name: configure Azure credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: ensure resource group exists
        run: |-
          set -x
          EXISTING_RESOURCE_GROUPS=$(az group list | jq -r '.[].name')
          if [[ "${EXISTING_RESOURCE_GROUPS}" == *"${RESOURCE_GROUP_NAME}"* ]]
          then
              echo "Resource group ${RESOURCE_GROUP_NAME} already exists - skipping create"
          else
              echo "Create resource group ${RESOURCE_GROUP_NAME}"
              az group create --name=${RESOURCE_GROUP_NAME} --location=${LOCATION}
          fi
      - name: ensure identity exists
        run: |-
          set -x
          EXISTING_IDENTITIES=$(az identity list | jq '.[].name')
          if [[ "${EXISTING_IDENTITIES}" == *"${IDENTITY_NAME}"* ]]
          then
              echo "Identity ${IDENTITY_NAME} already exists - skipping create"
          else
              echo "Create managed identity"
              az identity create -g ${RESOURCE_GROUP_NAME} -n ${IDENTITY_NAME}
          fi
      - name: create and assign role definition
        run: |-
          set -x
          EXISTING_ROLE_DEFINITION=$(az role definition list --custom-role-only --name "${IMAGE_ROLE_DEF_NAME}" | jq -r '.[].roleName')
          if [[ "${EXISTING_ROLE_DEFINITION}" == ${IMAGE_ROLE_DEF_NAME} ]]
          then
            echo "${IMAGE_ROLE_DEF_NAME} already exists - skipping create"
          else
            cp image_creation_role.json.tpl image_creation_role.json
            sed -i -e "s%<subscriptionID>%${SUBSCRIPTION_ID}%g" image_creation_role.json
            sed -i -e "s%<rgName>%${RESOURCE_GROUP_NAME}%g" image_creation_role.json
            sed -i -e "s%Azure Image Builder Service Image Creation Role%${IMAGE_ROLE_DEF_NAME}%g" image_creation_role.json
            cat image_creation_role.json
            az role definition create --role-definition ./image_creation_role.json
            identity_id=$(az identity list --resource-group auto-machine-images-rg | jq -r ".[] | select(.name == \"${IDENTITY_NAME}\") | .principalId")
            set +e
            let start=$(date '+%s')
            az role assignment create --assignee ${identity_id} --role "${IMAGE_ROLE_DEF_NAME}" --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}
            while [[ $? -ne 0 ]]
            do
                if [[ $(date '+%s') -gt $((start + 300)) ]]; then echo "Giving up after 5 minutes"; exit 1; fi
                echo "Role assignment failed - trying again in 10 seconds"
                sleep 10
                az role assignment create --assignee ${identity_id} --role "${IMAGE_ROLE_DEF_NAME}" --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}
            done
          fi
      - name: create image template
        run: |-
          set -x
          EXISTING_TEMPLATES=$(az resource list --name ${IMAGE_NAME} --resource-type 'microsoft.virtualmachineimages/imagetemplates' | jq '.[].name')
          create=true
          if [[ "${EXISTING_TEMPLATES}" == *"${IMAGE_NAME}"* ]]
          then
            if [[ ${{ inputs.recreate_template }} == true ]]
            then
              echo "Recreating template"
              resource_id=$(az resource list --name auto-neurodamus --resource-type 'microsoft.virtualmachineimages/imagetemplates' | jq -r '.[].id')
              az resource delete --ids ${resource_id}
            else
              echo "Template already exists - skipping creation"
              create=false
            fi
          fi
          if [[ ${create} == true ]]
          then
            cp image_template.json.tpl image_template.json
            sed -i -e "s%<subscriptionID>%${SUBSCRIPTION_ID}%g" image_template.json
            sed -i -e "s%<rgName>%${RESOURCE_GROUP_NAME}%g" image_template.json
            sed -i -e "s%<region>%${LOCATION}%g" image_template.json
            sed -i -e "s%<imageName>%${IMAGE_NAME}%g" image_template.json
            sed -i -e "s%<runOutputName>%${RUN_OUTPUT_NAME}%g" image_template.json
            sed -i -e "s%<imgBuilderId>%${TEMPLATE_IMAGE_BUILDER_ID}%g" image_template.json
            az resource create --resource-group ${RESOURCE_GROUP_NAME} --properties '@image_template.json' --is-full-object --resource-type Microsoft.VirtualMachineImages/imageTemplates --name ${IMAGE_NAME}
          fi
      - name: build image from template
        run: |-
          set -x
          if [[ ${{ inputs.build_image_from_template }} == true ]]
          then
            echo "Building image from template"
            az image builder run --name ${IMAGE_NAME} --subscription ${SUBSCRIPTION_ID} --resource-group ${RESOURCE_GROUP_NAME}
          fi
      - name: ensure image gallery exists
        run: |-
          set -x
          EXISTING_GALLERIES=$(az sig list --resource-group ${RESOURCE_GROUP_NAME} | jq -r '.[].name')
          if [[ "${EXISTING_GALLERIES}" == *"${GALLERY_NAME}"* ]]
          then
              echo "Image gallery ${GALLERY_NAME} already exists - skipping creation"
          else
              echo "Creating image gallery ${GALLERY_NAME}"
              az sig create  --gallery-name ${GALLERY_NAME} --resource-group  ${RESOURCE_GROUP_NAME} --location ${LOCATION}
          fi
      - name: ensure image definition exists
        run: |-
          set -x
          EXISTING_IMAGE_DEFINITIONS=$(az sig image-definition list --gallery-name ${GALLERY_NAME} --resource-group ${RESOURCE_GROUP_NAME} | jq -r '.[].name')
          if [[ "${EXISTING_IMAGE_DEFINITIONS}" == *"${IMAGE_NAME}"* ]]
          then
              echo "Image definition ${IMAGE_NAME} already exists - skipping creation"
          else
              echo "Creating image definition ${IMAGE_NAME}"
              az sig image-definition create --gallery-image-definition ${IMAGE_NAME} --gallery-name ${GALLERY_NAME} --offer ${IMAGE_NAME} --os-type Linux --publisher openbraininstitute --resource-group ${RESOURCE_GROUP_NAME} --sku ${IMAGE_VERSION} --architecture x64 --location ${LOCATION}
              provisioningState=Provisioning
              while [[ "${provisioningState}" != "Succeeded" ]]
              do
                  echo "Image definition state ${provisioningState} not ready yet... waiting"
                  sleep 5
                  provisioningState=$(az sig image-definition list --gallery-name ${GALLERY_NAME} --resource-group ${RESOURCE_GROUP_NAME} | jq -r ".[] | select(.name == \"${IMAGE_NAME}\") | .provisioningState")
              done
          fi
      - name: create image version
        run: |-
          set -x
          az sig image-version create --gallery-image-definition ${IMAGE_NAME} --gallery-image-version ${IMAGE_VERSION} --gallery-name ${GALLERY_NAME} --resource-group ${RESOURCE_GROUP_NAME} --location ${LOCATION} --managed-image ${IMAGE_NAME} --target-regions eastus=1 eastus2=1 westeurope=1
